### ISSUE TITLE
examples/heat fails with tensorflow 2.18.0

### ISSUE THREAD

**Issue by slitvinov** [cselab/odil#6]
I do
```
$ python3.11 -m ensurepip
$ python3.11 -m pip install numpy matplotlib tensorflow
$ python3.11 -m pip install git+https://github.com/cselab/odil.git
$ python3.11 heat.py
```
and `heat.py` fails with an error message
```$ python3.11 heat.py
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1731513700.689220 2926443 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1731513700.693199 2926443 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Traceback (most recent call last):
  File "/n/home13/slitvinov/odil/examples/heat/heat.py", line 615, in <module>
    main()
  File "/n/home13/slitvinov/odil/examples/heat/heat.py", line 608, in main
    odil.util.optimize(args, args.optimizer, problem, state, callback)
  File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/util.py", line 317, in optimize
    return optimize_grad(args, optname, problem, state, callback, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/util.py", line 300, in optimize_grad
    _, _, pinfo = loss_grad(arrays)
                  ^^^^^^^^^^^^^^^^^
  File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/util.py", line 269, in loss_grad
    loss, grads, terms, names, norms = problem.eval_loss_grad(state)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/core.py", line 1360, in eval_loss_grad
    loss, grads, terms, names, norms = self._eval_loss_grad(state)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/core.py", line 1183, in _eval_loss_grad_tf
    loss, grads, terms, norms = cache['func'](arrays)
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_filebje_7k7i.py", line 18, in tf__func
    ff = ag__.converted_call(ag__.ld(self).operator, (ag__.ld(ctx),), None, fscope)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/__autograph_generated_filecuudnzeh.py", line 107, in tf__operator_odil
    ag__.converted_call(ag__.ld(apply_bc_u), (ag__.ld(u_st),), None, fscope)
  File "/tmp/__autograph_generated_filecuudnzeh.py", line 85, in apply_bc_u
    ag__.if_stmt(ag__.ld(args).keep_init, if_body_1, else_body_1, get_state_2, set_state_2, (), 0)
  File "/tmp/__autograph_generated_filecuudnzeh.py", line 75, in if_body_1
    ag__.for_stmt(ag__.converted_call(ag__.ld(range), (3,), None, fscope_2), None, loop_body, get_state_1, set_state_1, (), {'iterate_names': 'i'})
  File "/tmp/__autograph_generated_filecuudnzeh.py", line 73, in loop_body
    ag__.ld(qm)[ag__.ld(i)] = ag__.converted_call(ag__.ld(mod).where, (ag__.ld(it) == 0, ag__.converted_call(ag__.ld(extrap), (ag__.ld(q)[ag__.ld(i)], ag__.ld(q0)[ag__.ld(i)][None, :]), None, fscope_2), ag__.ld(qm)[ag__.ld(i)]), None, fscope_2)
                                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/__autograph_generated_file75v3r0k_.py", line 11, in tf__extrap_linear
    u2 = 2 * ag__.ld(u1) - ag__.ld(u0)
         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
TypeError: in user code:

    File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/core.py", line 1155, in func  *
        ff = self.operator(ctx)
    File "/n/home13/slitvinov/odil/examples/heat/heat.py", line 69, in apply_bc_u  *
        qm[i] = mod.where(it == 0, extrap(q[i], q0[i][None, :]), qm[i])
    File "/n/home13/slitvinov/.local/lib/python3.11/site-packages/odil/core.py", line 1588, in extrap_linear  *
        u2 = 2 * u1 - u0

    TypeError: Input 'y' of 'Sub' Op has type float32 that does not match type float64 of argument 'x'.
```

I have
```
$ python3.11 -c 'import tensorflow as tf; print(tf.version.VERSION)'
2.18.0
$ python3.11 -c 'import numpy; print(numpy.version.version)'
2.0.2
$ cat /etc/*rel*
Rocky Linux release 8.9 (Green Obsidian)
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
Rocky Linux release 8.9 (Green Obsidian)
Rocky Linux release 8.9 (Green Obsidian)
Derived from Red Hat Enterprise Linux 8.9
Rocky Linux release 8.9 (Green Obsidian)
cpe:/o:rocky:rocky:8:GA
```

**Comment by pkarnakov** [comment]
Thanks you for reporting this issue! I have provided a fix in this commit: https://github.com/cselab/odil/commit/1356895bad056c8bade817c00c014060fa9af67b
